# Generated by Django 4.2.4 on 2023-08-31 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='subtitle',
            new_name='description',
        ),
    ]
